### ISSUE TITLE
I want remove without promt

### ISSUE THREAD

**Issue by mk148a** [kirillkovalenko/nssm#12]
Hi, i am it from my domain network. I need use nssm and remove some created with nssm services. but need remove without promt.
nssm remove <servicename>

to remove a service.  You will prompted for confirmation before the service 
is removed.  Try not to remove essential system services...

its need to work with quite and background, my users not need see it for this fixes.

**Comment by mk148a** [comment]
I handle it
https://i.hizliresim.com/ok149b.png

**Comment by mk148a** [comment]
İts not working :S please help me

**Comment by m00s** [comment]
👍

**Comment by kirillkovalenko** [comment]
THIS REPO IS NOT OWNED OR MONITORED BY THE AUTHOR OF THIS APPLICATION! REACH OUT TO HIM AT me@iain.cx
