### ISSUE TITLE
Deleting/Archiving log files

### ISSUE THREAD

**Issue by rohancme** [kirillkovalenko/nssm#13]
Is there a way to delete older log files? Right now when I run a service with log rotation turned on nssm keeps generating new log files which is bound to fill up the server disk soon. 

Is there a way around this?

**Comment by kirillkovalenko** [comment]
THIS REPO IS NOT OWNED OR MONITORED BY THE AUTHOR OF THIS APPLICATION! REACH OUT TO HIM AT me@iain.cx
