### ISSUE TITLE
Can't delete nssm.exe in windows 2008

### ISSUE THREAD

**Issue by tianlin** [kirillkovalenko/nssm#14]
When I delete nssm in 2008,  windows reports "it's used by windows event log". So how can I remove nssm.exe without reboot.

![qq20171226-0](https://user-images.githubusercontent.com/3477148/34354262-019421b2-ea68-11e7-8b10-1b0304f68b6a.jpg)

**Comment by kirillkovalenko** [comment]
THIS REPO IS NOT OWNED OR MONITORED BY THE AUTHOR OF THIS APPLICATION REACH OUT TO HIM AT me@iain.cx to THIS REPO IS NOT OWNED OR MONITORED BY THE AUTHOR OF THIS APPLICATION! REACH OUT TO HIM AT me@iain.cx
