### ISSUE TITLE
Trojan Virus on NSSM

### ISSUE THREAD

**Issue by alasserr** [kirillkovalenko/nssm#15]
Hi,
I downloaded last week (25/04/2018) the software nssm from the official page https://nssm.cc/download (last version 2.24) ... and it appears that this is infected by a Trojan "Trojan.Agent.bcpc/ Trojan.Instsrv".
I do not know about source code and real ownership, but I've already contacted Iain Patterson by email to inform him. I think some things have to be checked out ...

Adrien Lasserre

**Comment by kirillkovalenko** [comment]
THIS REPO IS NOT OWNED OR MONITORED BY THE AUTHOR OF THIS APPLICATION! REACH OUT TO HIM AT me@iain.cx
