### ISSUE TITLE
Start parameter in the docs and in the README.txt for the delayed auto start isn't correct

### ISSUE THREAD

**Issue by trsrc** [kirillkovalenko/nssm#16]
From README.txt

The Start parameter is used to query or set the startup type of the service.
Valid service startup types are as follows:

  SERVICE_AUTO_START: Automatic startup at boot.
  **SERVICE_DELAYED_START: Delayed startup at boot.**
  SERVICE_DEMAND_START: Manual service startup.
  SERVICE_DISABLED: The service is disabled.

Which is wrong, for delayed startup at boot you have to use: **SERVICE_DELAYED_AUTO_START**.

Same problem is on the webpage:
- https://nssm.cc/commands

**Comment by kirillkovalenko** [comment]
THIS REPO IS NOT OWNED OR MONITORED BY THE AUTHOR OF THIS APPLICATION! REACH OUT TO HIM AT me@iain.cx
