### ISSUE TITLE
couldn't set startup parameters for the service!deleting the service.

### ISSUE THREAD

**Issue by ForgotLove** [kirillkovalenko/nssm#19]
when I was doing the following configuration,error appears like the following picture.It's a python service.
![image](https://user-images.githubusercontent.com/5884209/43623222-badfe67c-9712-11e8-8079-171536692d51.png)

**Comment by AMeloYi** [comment]
The same problem... Can not find any solution with Google. Anyone knows how to solve it ?

**Comment by ForgotLove** [comment]
The operating system is  Windows Server 2008 R2 Enterprise 64-bit.

**Comment by kirillkovalenko** [comment]
THIS REPO IS NOT OWNED OR MONITORED BY THE AUTHOR OF THIS APPLICATION! REACH OUT TO HIM AT me@iain.cx

**Comment by autukill** [comment]
Turn off the anti-virus software

**Comment by DAGENJI** [comment]
Same question, due to 360 security software

**Comment by yxrswx** [comment]
close 360
