### ISSUE TITLE
PlexRequest won't start as service

### ISSUE THREAD

**Issue by damianeickhoff** [kirillkovalenko/nssm#2]
<strike>Hi,

<strike>I have this problem with PlexRequest as a service. To add PlexRequest to services I use Nssm. <strike>PlexRequest uses Meteor to run. I created a .bat file, the .bat file itself is working correctly.
<strike>When i'm starting the service I get the error: Windows could not start the PlexRequest service <strike>on local computer. It doen't give any errors. Do you guys know what the problem is?

Kind Regards</strike>

Fixed it by adding .vbs to Task Scheduler.

**Comment by kirillkovalenko** [comment]
Hi, 
I'm not an owner of this code, Iain Patterson is. 
This repo is just a mirror of Iain's original repo at https://nssm.cc

**Comment by kirillkovalenko** [comment]
THIS REPO IS NOT OWNED OR MONITORED BY THE AUTHOR OF THIS APPLICATION! REACH OUT TO HIM AT me@iain.cx
