### ISSUE TITLE
NSSM hang when AppKillProcessTree = 0 and child-process keep running

### ISSUE THREAD

**Issue by betonetotbo** [kirillkovalenko/nssm#22]
I'm using NSSM to launch my java application.

The problem is about a child-process who is launched from my application (another java JAR application to perform the update of my main application).

This child-process will perform a stop and a start over my NSSM service.

Here is the problem, when the child-process perform the STOP of the service, the service  stay in state "stop pending" because the NSSM is wating for the child-process to stop too...

I have tried to set the `nssm.exe set "my service name" AppKillProcessTree 0` but this configuration only tells to NSSM to prevent the kill of the process tree (children).

I tried to launch my child-process using the `cmd.exe /c start java -jar ...` expecting that NSSM will unknown this "child of a dead child process" but it also doesn't works and NSSM hangs too!

**Comment by kirillkovalenko** [comment]
THIS REPO IS NOT OWNED OR MONITORED BY THE AUTHOR OF THIS APPLICATION! REACH OUT TO HIM AT me@iain.cx
