### ISSUE TITLE
Where is 2.25 release? 

### ISSUE THREAD

**Issue by thegoatherder** [kirillkovalenko/nssm#25]
Hi, the changelog mentions several useful features in v2.25: `dump` and `list`
I can't find v2.25 anywhere - only v2.24 seems available to download and on package managers like choco.
Is v2.25 released or unstable?

Also can you confirm if nssm works on Windows Server? (2012, 2016, etc)

Thanks!

**Comment by kirillkovalenko** [comment]
THIS REPO IS NOT OWNED OR MONITORED BY THE AUTHOR OF THIS APPLICATION! REACH OUT TO HIM AT me@iain.cx

**Comment by vcantrell** [comment]
I compiled v2.25 from the source code at [https://git.nssm.cc/nssm/nssm](https://git.nssm.cc/nssm/nssm) - Seems to work just as well as 2.24, plus the added changes with the 2.25 upgrade:

[https://clipp.link/nssm2-25](https://clipp.link/nssm2-25)

**Comment by booter-scooter** [comment]
> I compiled v2.25 from the source code at https://git.nssm.cc/nssm/nssm - Seems to work just as well as 2.24, plus the added changes with the 2.25 upgrade:
> 
> https://clipp.link/nssm2-25

So, does that mean compiling NSSM for oneself is the ONLY means by which to obtain the most recent version? Is there truly no place to just download the executable file directly or a zip file containing the NSSM executable? Thanks for any help you can provide regarding this matter.

**Comment by booter-scooter** [comment]
> Hi, the changelog mentions several useful features in v2.25: `dump` and `list` I can't find v2.25 anywhere - only v2.24 seems available to download and on package managers like choco. Is v2.25 released or unstable?
> 
> Also can you confirm if nssm works on Windows Server? (2012, 2016, etc)
> 
> Thanks!

I'm wondering the same. Did you ever manage to locate a source for just downloading the actual NSSM executable file? 

Thanks.

**Comment by booter-scooter** [comment]
> I compiled v2.25 from the source code at https://git.nssm.cc/nssm/nssm - Seems to work just as well as 2.24, plus the added changes with the 2.25 upgrade:
> 
> https://clipp.link/nssm2-25

That link just directs you to the Microsoft CoPilot website.

**Comment by vcantrell** [comment]
> > I compiled v2.25 from the source code at https://git.nssm.cc/nssm/nssm - Seems to work just as well as 2.24, plus the added changes with the 2.25 upgrade:
> > https://clipp.link/nssm2-25
> 
> That link just directs you to the Microsoft CoPilot website.

You're right... I fixed the link. 

Makes me wonder about the integrity if my Shlink data though... because there's links on either side of the date I created that link, but that link was somehow 'removed' 🤔

Either way. It's fixed now.

**Comment by kp-savvy** [comment]
> > > I compiled v2.25 from the source code at https://git.nssm.cc/nssm/nssm - Seems to work just as well as 2.24, plus the added changes with the 2.25 upgrade:
> > > https://clipp.link/nssm2-25
> > 
> > 
> > That link just directs you to the Microsoft CoPilot website.
> 
> You're right... I fixed the link.
> 
> Makes me wonder about the integrity if my Shlink data though... because there's links on either side of the date I created that link, but that link was somehow 'removed' 🤔
> 
> Either way. It's fixed now.

Hello, that link redirects me to mega.nz cloud and the uploaded file was a json file.
Is there any way to find a nssm2-25.exe file?

**Comment by vcantrell** [comment]
Just tested that link... it redirects to a zip file on MEGA, and when you extract that zip file, under the win64 folder there's an exe for nssm 2.5 
<img width="830" alt="Screenshot 2024-07-05 at 4 39 52 PM" src="https://github.com/kirillkovalenko/nssm/assets/13757016/b7663b80-8ff9-4a3d-9e7e-8d68849c7816">
<img width="1421" alt="Screenshot 2024-07-05 at 4 44 54 PM" src="https://github.com/kirillkovalenko/nssm/assets/13757016/b6349188-c2bd-467f-ab56-e8dc06c6a7f8">

**Comment by kenrmayfield** [comment]
@vcantrell 
@kirillkovalenko 

This is still a Issue.

Where is the link for 2.25?

Do you have to Compile?

**Comment by kirillkovalenko** [comment]
@kenrmayfield THIS REPO IS NOT OWNED OR MONITORED BY THE AUTHOR OF THIS APPLICATION! REACH OUT TO HIM AT [me@iain.cx](mailto:me@iain.cx)
