### ISSUE TITLE
Last installation i had a GUI, now i have console only (and a paramter help message box)

### ISSUE THREAD

**Issue by jayjupdhig** [kirillkovalenko/nssm#28]
Hi

Last installation i had a GUI, now i have console only (and a paramter help message box)

Why?

Whrere can i get the GUI edition?

Thx for feedback.

**Comment by kirillkovalenko** [comment]
THIS REPO IS NOT OWNED OR MONITORED BY THE AUTHOR OF THIS APPLICATION! REACH OUT TO HIM AT me@iain.cx

**Comment by jayjupdhig** [comment]
OK thx
