### ISSUE TITLE
nssm.cc has a bugs page that tells users to report bugs, but there is no link to how they can report them anywhere on the site.

### ISSUE THREAD

**Issue by Tanz0rz** [kirillkovalenko/nssm#5]
It is entirely possible that your nssm service will be used by someone who does not know anything about github. 

On the bugs page, I suggest adding a link to the issues tab of this github repo.

**Comment by kirillkovalenko** [comment]
I'm not an owner of this code, Iain Patterson is.
This repo is just a mirror of Iain's original repo at https://nssm.cc
